//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_UI.StudentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentService.IStudentService")]
    public interface IStudentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/CheckConnection", ReplyAction="http://tempuri.org/IStudentService/CheckConnectionResponse")]
        string CheckConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/CheckConnection", ReplyAction="http://tempuri.org/IStudentService/CheckConnectionResponse")]
        System.Threading.Tasks.Task<string> CheckConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetAccountTypes", ReplyAction="http://tempuri.org/IStudentService/GetAccountTypesResponse")]
        string GetAccountTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetAccountTypes", ReplyAction="http://tempuri.org/IStudentService/GetAccountTypesResponse")]
        System.Threading.Tasks.Task<string> GetAccountTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/SignUp", ReplyAction="http://tempuri.org/IStudentService/SignUpResponse")]
        string SignUp(string username, string password, int accountTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/SignUp", ReplyAction="http://tempuri.org/IStudentService/SignUpResponse")]
        System.Threading.Tasks.Task<string> SignUpAsync(string username, string password, int accountTypeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/Login", ReplyAction="http://tempuri.org/IStudentService/LoginResponse")]
        string Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/Login", ReplyAction="http://tempuri.org/IStudentService/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/ResetPassword", ReplyAction="http://tempuri.org/IStudentService/ResetPasswordResponse")]
        string ResetPassword();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/ResetPassword", ReplyAction="http://tempuri.org/IStudentService/ResetPasswordResponse")]
        System.Threading.Tasks.Task<string> ResetPasswordAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudents", ReplyAction="http://tempuri.org/IStudentService/GetStudentsResponse")]
        string GetStudents(string accessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudents", ReplyAction="http://tempuri.org/IStudentService/GetStudentsResponse")]
        System.Threading.Tasks.Task<string> GetStudentsAsync(string accessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetTeachers", ReplyAction="http://tempuri.org/IStudentService/GetTeachersResponse")]
        string GetTeachers(string accessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetTeachers", ReplyAction="http://tempuri.org/IStudentService/GetTeachersResponse")]
        System.Threading.Tasks.Task<string> GetTeachersAsync(string accessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetGrades", ReplyAction="http://tempuri.org/IStudentService/GetGradesResponse")]
        string GetGrades(int studentID, int teacherID, string accessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetGrades", ReplyAction="http://tempuri.org/IStudentService/GetGradesResponse")]
        System.Threading.Tasks.Task<string> GetGradesAsync(int studentID, int teacherID, string accessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentRating", ReplyAction="http://tempuri.org/IStudentService/GetStudentRatingResponse")]
        string GetStudentRating(int studentID, int teacherID, string accessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentRating", ReplyAction="http://tempuri.org/IStudentService/GetStudentRatingResponse")]
        System.Threading.Tasks.Task<string> GetStudentRatingAsync(int studentID, int teacherID, string accessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/RateTeacher", ReplyAction="http://tempuri.org/IStudentService/RateTeacherResponse")]
        string RateTeacher(int studentID, int teacherID, int rate, string accessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/RateTeacher", ReplyAction="http://tempuri.org/IStudentService/RateTeacherResponse")]
        System.Threading.Tasks.Task<string> RateTeacherAsync(int studentID, int teacherID, int rate, string accessToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServiceChannel : Student_UI.StudentService.IStudentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<Student_UI.StudentService.IStudentService>, Student_UI.StudentService.IStudentService {
        
        public StudentServiceClient() {
        }
        
        public StudentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckConnection() {
            return base.Channel.CheckConnection();
        }
        
        public System.Threading.Tasks.Task<string> CheckConnectionAsync() {
            return base.Channel.CheckConnectionAsync();
        }
        
        public string GetAccountTypes() {
            return base.Channel.GetAccountTypes();
        }
        
        public System.Threading.Tasks.Task<string> GetAccountTypesAsync() {
            return base.Channel.GetAccountTypesAsync();
        }
        
        public string SignUp(string username, string password, int accountTypeID) {
            return base.Channel.SignUp(username, password, accountTypeID);
        }
        
        public System.Threading.Tasks.Task<string> SignUpAsync(string username, string password, int accountTypeID) {
            return base.Channel.SignUpAsync(username, password, accountTypeID);
        }
        
        public string Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public string ResetPassword() {
            return base.Channel.ResetPassword();
        }
        
        public System.Threading.Tasks.Task<string> ResetPasswordAsync() {
            return base.Channel.ResetPasswordAsync();
        }
        
        public string GetStudents(string accessToken) {
            return base.Channel.GetStudents(accessToken);
        }
        
        public System.Threading.Tasks.Task<string> GetStudentsAsync(string accessToken) {
            return base.Channel.GetStudentsAsync(accessToken);
        }
        
        public string GetTeachers(string accessToken) {
            return base.Channel.GetTeachers(accessToken);
        }
        
        public System.Threading.Tasks.Task<string> GetTeachersAsync(string accessToken) {
            return base.Channel.GetTeachersAsync(accessToken);
        }
        
        public string GetGrades(int studentID, int teacherID, string accessToken) {
            return base.Channel.GetGrades(studentID, teacherID, accessToken);
        }
        
        public System.Threading.Tasks.Task<string> GetGradesAsync(int studentID, int teacherID, string accessToken) {
            return base.Channel.GetGradesAsync(studentID, teacherID, accessToken);
        }
        
        public string GetStudentRating(int studentID, int teacherID, string accessToken) {
            return base.Channel.GetStudentRating(studentID, teacherID, accessToken);
        }
        
        public System.Threading.Tasks.Task<string> GetStudentRatingAsync(int studentID, int teacherID, string accessToken) {
            return base.Channel.GetStudentRatingAsync(studentID, teacherID, accessToken);
        }
        
        public string RateTeacher(int studentID, int teacherID, int rate, string accessToken) {
            return base.Channel.RateTeacher(studentID, teacherID, rate, accessToken);
        }
        
        public System.Threading.Tasks.Task<string> RateTeacherAsync(int studentID, int teacherID, int rate, string accessToken) {
            return base.Channel.RateTeacherAsync(studentID, teacherID, rate, accessToken);
        }
    }
}
